env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - plugin:storybook/recommended
  - airbnb
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules:
  no-underscore-dangle: ['error', {
    allow: ['__filename', '__dirname'],
  }]
