env:
  browser: true
  es2021: true
extends:
  - airbnb
  - plugin:react/recommended
  - plugin:react/jsx-runtime
  - plugin:storybook/recommended
overrides: [
  {
    files: main.js,
    rules: {
      import/extensions: off
    }
  }
]
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules:
  no-underscore-dangle: ['error', {
    allow: ['__filename', '__dirname'],
  }]
  react/function-component-definition: ['error', {
    namedComponents: arrow-function,
    unnamedComponents: arrow-function
  }]
